version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - api-service

  auth-service:
    build: ./auth-service
    environment:
      - MONGO_URI=mongodb://mongodb:27017/auth
      - JWT_SECRET=your-secret-key
    ports:
      - "3001:3000"
    depends_on:
      - mongodb

  api-service:
    build: ./api-service
    environment:
      - MONGO_URI=mongodb://mongodb:27017/api
    ports:
      - "3002:3001"
    depends_on:
      - mongodb

  mongodb:
    build: ./db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: